In [6]:
import pandas as pd
import numpy as np

In [7]:
import pandas as pd

df = pd.read_excel(
    r"C:\Users\Dell\OneDrive\Desktop\Retail-Customer-Intelligence\data\raw\OnlineRetail.xlsx"
)

In [8]:
clean_df = df.copy()

In [9]:
clean_df = clean_df.dropna(
    subset=["CustomerID"]
)

In [10]:
print(df.shape)

print(clean_df.shape)

(541909, 8)
(406829, 8)

In [11]:
clean_df = clean_df.drop_duplicates()

In [12]:
clean_df.duplicated().sum()

np.int64(0)

In [13]:
clean_df = clean_df[
    clean_df["Quantity"] > 0
]

In [14]:
clean_df = clean_df[
    clean_df["UnitPrice"] > 0
]

In [15]:
clean_df["InvoiceDate"] = pd.to_datetime(
    clean_df["InvoiceDate"]
)

In [16]:
clean_df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [17]:
#feature engineering
clean_df["TotalPrice"] = (
      clean_df["Quantity"]
      *
      clean_df["UnitPrice"]
)

In [18]:
clean_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [19]:
clean_df["Year"] = (
    clean_df["InvoiceDate"].dt.year
)

clean_df["Month"] = (
    clean_df["InvoiceDate"].dt.month
)

clean_df["Day"] = (
    clean_df["InvoiceDate"].dt.day
)

clean_df["Hour"] = (
    clean_df["InvoiceDate"].dt.hour
)

In [20]:
clean_df.to_csv(
"C:/Users/Dell/OneDrive/Desktop/Retail-Customer-Intelligence/data/cleaned/clean_retail.csv",
index=False
)

In [21]:
#sql
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: pymysql in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (1.2.0)

In [22]:
import sqlalchemy
import pymysql

print("Installed successfully")

Installed successfully

In [23]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Simran%402004@localhost/retail_db"
)

connection = engine.connect()

print("Connected successfully")

Connected successfully

In [24]:
clean_df.to_sql(
    name="retail_data",
    con=engine,
    if_exists="replace",
    index=False
)

print("Data loaded successfully")

Data loaded successfully

In [26]:
query = """
SELECT
Country,
COUNT(*) AS total_orders
FROM retail_data
GROUP BY Country
ORDER BY total_orders DESC
LIMIT 10
"""

pd.read_sql(query, engine)

          Country  total_orders
0  United Kingdom        349203
1         Germany          9025
2          France          8326
3            EIRE          7226
4           Spain          2479
5     Netherlands          2359
6         Belgium          2031
7     Switzerland          1841
8        Portugal          1453
9       Australia          1181

In [27]:
query = """
SELECT
COUNT(DISTINCT CustomerID) AS total_customers,
COUNT(DISTINCT InvoiceNo) AS total_orders,
SUM(TotalPrice) AS revenue,
AVG(TotalPrice) AS avg_order_value
FROM retail_data
"""

pd.read_sql(query, engine)

   total_customers  total_orders       revenue  avg_order_value
0             4338         18532  8.887209e+06          22.6315